<a href="https://colab.research.google.com/github/EUNBI-J/blog/blob/master/Test_20200602.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sklearn
print(sklearn.__version__)


0.22.2.post1


In [0]:
from sklearn.datasets import load_iris                 #Dataset : iris
from sklearn.tree import DecisionTreeClassifier        #Classification
from sklearn.model_selection import train_test_split   #Evaluation :Cross-validation

In [0]:
import pandas as pd

In [0]:
iris = load_iris()
iris
iris.data
#len(iris.data)
#iris.keys()
#iris.values()
iris.target
iris.target_names
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [0]:
# iris dataset에서 feature 해당하는 데이터
print(iris.data[0:10])
print(iris.feature_names)      # feature 데이터에 대한 설명(이름)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [0]:
# iris dataset에서 label 해당하는 데이터
print(iris.target)
print(iris.target_names)       # label 데이터에 대한 설명(이름)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [0]:
# iris dataset 가독성을 위한 DataFrame 작업 :
df_iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df_iris.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [0]:
# iris dataset 중, feature에 대한 Label 정보 연결
df_iris['label'] = iris.target
df_iris.head(10)

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  label
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0
3                4.6               3.1  ...               0.2      0
4                5.0               3.6  ...               0.2      0
5                5.4               3.9  ...               0.4      0
6                4.6               3.4  ...               0.3      0
7                5.0               3.4  ...               0.2      0
8                4.4               2.9  ...               0.2      0
9                4.9               3.1  ...               0.1      0

[10 rows x 5 columns]

In [0]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, 
                                                    test_size=0.2,          # train:test = 80:20
                                                    random_state=9)         # 예컨대, seed번호

In [0]:
print(len(X_train), len(y_train))
#print(X_train)
#print(y_train)

120 120


In [0]:
print(len(X_test), len(y_test))
#print(X_test)
#print(y_test)

30 30


In [0]:
# 분류알고리즘 객체 생성:
dt_clf = DecisionTreeClassifier(random_state=9)

In [0]:
# 학습 수행:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=9, splitter='best')

In [0]:
# 학습이 완료된 객체로부터 Test 데이터 예측 수행:
y_predict = dt_clf.predict(X_test)

In [0]:
y_predict

array([2, 1, 2, 2, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0,
       2, 0, 2, 1, 0, 2, 0, 2])

In [0]:
pd.DataFrame({"y_test": y_test, "predict": y_predict, "Accuracy": y_test == y_predict})

y_test  predict  Accuracy
0        2        2      True
1        1        1      True
2        2        2      True
3        2        2      True
4        1        1      True
5        0        0      True
6        0        0      True
7        0        0      True
8        1        1      True
9        0        0      True
10       0        0      True
11       1        1      True
12       1        1      True
13       1        1      True
14       0        0      True
15       1        1      True
16       0        0      True
17       1        1      True
18       2        2      True
19       0        0      True
20       0        0      True
21       0        0      True
22       2        2      True
23       0        0      True
24       2        2      True
25       1        1      True
26       0        0      True
27       2        2      True
28       0        0      True
29       2        2      True

In [0]:
from sklearn.metrics import accuracy_score
#accuracy_score(y_test, predict)
print(f'Accuracy: {accuracy_score(y_test, y_predict)}')

Accuracy: 1.0


## 실습 2: 

### Kaggle - Titanic: Machine Learning from Disaster


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
df_titanic = pd.read_csv('/content/drive/My Drive/BIGDATA_CLASS/20200602/data/train.csv')
df_titanic.head(3)

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S

[3 rows x 12 columns]